La gui è strutturata in 5 tab 

- Project
- Setup
- Segmentation
- SVG Editor
- Post Processing

Come altri elementi della suite pypottery, pypotterytrace supporta i progetti. Per creare un progetto clicca su new project o su create tour first project. una finestra di dialogo darà la possibilità di dare il nome a un progetto, così come una descrizione opzionale e un'icona. Una volta creato il progetto, viene chiesto se si vogliono caricare le immagini. Se la risposta è positiva, un dialog di sistema permetterà di scegliere le immagini. Altrimenti è possibile scegliere le immagini dalla tab setup.

### Setup

la tab  bipartita: sulla sinistra è presente una galleria con le immagini, mentre a destra è possibile scegliere e selezionare un modello di SAM2 per la segmentazione. Seleziondando verrà scaricato automaticamente.

Cliccando su start processing si passa alla slide segmentation.

--> SE CARICO LE IMMAGINI CREANDO IL PROGETTO FUNZIONA, SE LE CARICO DA SETUP NO, DEVI CORREGGERE QUESTO COMPORTAMENTO.

