project:
  type: website
  output-dir: ../docs
  render:
    - "!article.qmd"
    - "*.qmd"
    - "*/*.qmd"
  resources:
    - anim-kit/*.css
    - anim-kit/*.js
    - animations/*.html
    - animations/*.png
    - animations/*.ico

website:
  title: "PyPottery"
  repo-url: https://github.com/lrncrd/PyPottery
  repo-actions: [source, issue]
  navbar:
    logo: "logo_mark.png"
    left:
      - text: "Project Home"
        href: index.html
      - text: "Download Suite"
        href: https://github.com/lrncrd/PyPottery/releases/latest
      - text: "Publications"
        href: docs_home.qmd#academic-citations
    right:
      - icon: github
        href: https://github.com/lrncrd/PyPottery
        aria-label: GitHub
  sidebar:
    collapse-level: 1
    style: "docked"
    search: false
    contents:
      - text: "Suite Overview"
        href: docs_home.qmd
      - text: "Suite Installation"
        href: suite_installation.qmd
      - section: "PyPotteryLens"
        contents:
          - pypotterylens/index.qmd
          - pypotterylens/usage.qmd
          - pypotterylens/version_history.qmd
      - section: "PyPotteryScan"
        contents:
          - pypotteryscan/index.qmd
          - pypotteryscan/usage.qmd
          - pypotteryscan/version_history.qmd
      - section: "PyPotteryInk"
        contents:
          - pypotteryink/index.qmd
          - pypotteryink/usage.qmd
          - pypotteryink/advanced.qmd
          - pypotteryink/model_zoo.qmd
          - pypotteryink/api.qmd
          - pypotteryink/version_history.qmd
      - section: "PyPotteryTrace"
        contents:
          - pypotterytrace/index.qmd
          - pypotterytrace/usage.qmd
          - pypotterytrace/technical_reference.qmd
          - pypotterytrace/version_history.qmd
      - section: "PyPotteryLayout"
        contents:
          - pypotterylayout/index.qmd
          - pypotterylayout/usage.qmd
          - pypotterylayout/version_history.qmd
      - text: "Suite Version History"
        href: suite_version.qmd
      - text: "Open Source & Community"
        href: community.qmd
      - contact.qmd
      - acknowledgment.qmd

format:
  html:
    theme:
      light: flatly
    css: styles.css
    include-after-body: _footer.html
    toc: true
